-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [0] = {
        ["type"] = "WScreen",
        ["name"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS",
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1280,
                    ["h"] = 800,
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1280,
                            ["h"] = 800,
                        },
                        ["split_tree"] = {
                            ["regparams"] = {
                                ["mode"] = 1,
                                ["type"] = "WFrame",
                                ["name"] = "Notion WFrame<2>",
                                ["managed"] = {
                                    [1] = {
                                        ["type"] = "WGroupCW",
                                        ["name"] = "WGroupCW",
                                        ["hidden"] = true,
                                        ["geom"] = {
                                            ["y"] = 20,
                                            ["x"] = 3,
                                            ["w"] = 1274,
                                            ["h"] = 777,
                                        },
                                        ["sizepolicy"] = "full",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WClientWin",
                                                ["bottom"] = true,
                                                ["windowid"] = 10485763,
                                                ["checkcode"] = 1,
                                                ["sizepolicy"] = "full",
                                                ["geom"] = {
                                                    ["y"] = 3,
                                                    ["x"] = 1,
                                                    ["w"] = 1273,
                                                    ["h"] = 771,
                                                },
                                                ["level"] = 1,
                                            },
                                        },
                                        ["level"] = 0,
                                    },
                                    [2] = {
                                        ["type"] = "WGroupCW",
                                        ["name"] = "WGroupCW<2>",
                                        ["hidden"] = true,
                                        ["geom"] = {
                                            ["y"] = 20,
                                            ["x"] = 3,
                                            ["w"] = 1274,
                                            ["h"] = 777,
                                        },
                                        ["sizepolicy"] = "full",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WClientWin",
                                                ["bottom"] = true,
                                                ["windowid"] = 14680309,
                                                ["checkcode"] = 2,
                                                ["sizepolicy"] = "full",
                                                ["geom"] = {
                                                    ["y"] = 0,
                                                    ["x"] = 0,
                                                    ["w"] = 1274,
                                                    ["h"] = 777,
                                                },
                                                ["level"] = 1,
                                            },
                                        },
                                        ["level"] = 0,
                                    },
                                    [3] = {
                                        ["type"] = "WGroupCW",
                                        ["name"] = "WGroupCW<3>",
                                        ["hidden"] = true,
                                        ["geom"] = {
                                            ["y"] = 20,
                                            ["x"] = 3,
                                            ["w"] = 1274,
                                            ["h"] = 777,
                                        },
                                        ["sizepolicy"] = "full",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WClientWin",
                                                ["bottom"] = true,
                                                ["windowid"] = 14680485,
                                                ["checkcode"] = 3,
                                                ["sizepolicy"] = "full",
                                                ["geom"] = {
                                                    ["y"] = 0,
                                                    ["x"] = 0,
                                                    ["w"] = 1274,
                                                    ["h"] = 777,
                                                },
                                                ["level"] = 1,
                                            },
                                        },
                                        ["level"] = 0,
                                    },
                                    [4] = {
                                        ["type"] = "WGroupCW",
                                        ["name"] = "WGroupCW<1>",
                                        ["geom"] = {
                                            ["y"] = 20,
                                            ["x"] = 3,
                                            ["w"] = 1274,
                                            ["h"] = 777,
                                        },
                                        ["switchto"] = true,
                                        ["sizepolicy"] = "full",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WClientWin",
                                                ["bottom"] = true,
                                                ["windowid"] = 12583075,
                                                ["checkcode"] = 4,
                                                ["sizepolicy"] = "full",
                                                ["geom"] = {
                                                    ["y"] = 6,
                                                    ["x"] = 0,
                                                    ["w"] = 1274,
                                                    ["h"] = 765,
                                                },
                                                ["level"] = 1,
                                            },
                                        },
                                        ["level"] = 0,
                                    },
                                },
                            },
                            ["type"] = "WSplitRegion",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["y"] = 161,
                            ["x"] = 336,
                            ["w"] = 589,
                            ["h"] = 399,
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                        ["bottom"] = true,
                        ["level"] = 1025,
                        ["mode"] = 0,
                        ["managed"] = {
                            [1] = {
                                ["type"] = "WGroupCW",
                                ["name"] = "WGroupCW<4>",
                                ["geom"] = {
                                    ["y"] = 22,
                                    ["x"] = 5,
                                    ["w"] = 579,
                                    ["h"] = 372,
                                },
                                ["switchto"] = true,
                                ["sizepolicy"] = "full",
                                ["managed"] = {
                                    [1] = {
                                        ["type"] = "WClientWin",
                                        ["bottom"] = true,
                                        ["windowid"] = 18874371,
                                        ["checkcode"] = 5,
                                        ["sizepolicy"] = "full",
                                        ["geom"] = {
                                            ["y"] = 0,
                                            ["x"] = 0,
                                            ["w"] = 579,
                                            ["h"] = 372,
                                        },
                                        ["level"] = 1,
                                    },
                                },
                                ["level"] = 0,
                            },
                        },
                        ["sizepolicy"] = "free_glue",
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["pseudomodal"] = true,
                ["level"] = 1,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1280,
                    ["h"] = 800,
                },
                ["hidden"] = true,
            },
        },
    },
}

